name: CI

on:
  push:
    branches:
      - main
      - lab3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Make cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Python initialization
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install needed dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          pip install flake8
          flake8 .

      - name: Run pytest
        run: |
          pytest

      - name: Snyk check
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --code

  deploy:
    runs-on:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t devops-lab app_python
          docker tag devops-lab exemplerie/devops-lab
          docker push exemplerie/devops-lab


